### PR TITLE
Update version to 2.5

### PR DESCRIPTION
**Pull request by michalciolek**
You must create a new tag 2.5

Fix for #78

### CODE REVIEW

**Comment by michalciolek** [comment]
@kstenerud change tag 2.5 to a38694413707f8ecfbc5e4237064c4870a0b1542

**Comment by michalciolek** [comment]
now is OK

to close

**Comment by oriolblanc** [comment]
:+1:

**Comment by oriolblanc** [comment]
Do you will update the CocoaPods/Specs repo as well ?

**Comment by kstenerud** [comment]
I'm still stuck with this issue due to the demo app using cocos2d: https://github.com/kstenerud/ObjectAL-for-iPhone/issues/74

I'll see if I can sort it out.

**Comment by oriolblanc** [comment]
@kstenerud ok then

**Pull request merged**
